### ISSUE TITLE
Add option to disable console logs from API Server in BitBurner client

### ISSUE THREAD

**Issue by smolgumball** [hexnaught/vscode-bitburner-connector#6]
Very large and frequent debug logs are printed to the Electron dev tools when sending files from BitBurner. Would love an option to disable those, or perhaps filter them by some kind of log-level?

Not sure if this is the right place to suggest this, though! Let me know and I can recreate over on the official BitBurner client repo if that's helpful ✨ 

![image](https://user-images.githubusercontent.com/53015256/147900415-fae1a406-8034-42c2-b053-8c01894df9af.png)

**Comment by hexnaught** [comment]
@smolgumball I think this one is worth raising in the repo of the Game rather than here!

Will close the issue here.
